import { NextResponse } from 'next/server';

export async function GET() {
  const data = [
    {
      id: 1,
      name: "Statue of Unity",
      description: "The world’s tallest statue, depicting Sardar Vallabhbhai Patel in Kevadia.",
      image: "/tourism/u.jpg",
      lat: 21.8380,
      lon: 73.7191,
      address: "Kevadia, Narmada district, Gujarat",
      category: "Monument",
    },
    {
      id: 2,
      name: "Champaner-Pavagadh Archaeological Park",
      description: "UNESCO World Heritage site with forts, temples, palaces from 8th–14th centuries.",
      image: "/tourism/champaner.jpg",
      lat: 22.5292,
      lon: 73.4988,
      address: "Panchmahal district, Gujarat",
      category: "Heritage",
    },
    {
      id: 3,
      name: "Great Rann of Kutch",
      description: "Vast salt desert hosting the annual Rann Utsav festival with cultural programs.",
      image: "/tourism/maxresdefault.jpg",
      lat: 23.7333,
      lon: 69.7833,
      address: "Kutch district, Gujarat",
      category: "Nature",
    },
    {
      id: 4,
      name: "Gir National Park",
      description: "The only natural habitat of Asiatic lions, rich in wildlife and biodiversity.",
      image: "/tourism/gir.jpg",
      lat: 21.1240,
      lon: 70.8150,
      address: "Gir Somnath district, Gujarat",
      category: "Wildlife",
    },
    {
      id: 5,
      name: "Sun Temple, Modhera",
      description: "An intricately carved 11th-century temple dedicated to the sun god.",
      image: "/tourism/download.jpg",
      lat: 23.0340,
      lon: 72.5390,
      address: "Modhera, Mehsana district, Gujarat",
      category: "Architecture",
    },
    {
      id: 6,
      name: "Kankaria Lake",
      description: "A vibrant artificial lake in Ahmedabad with zoo, toy train, water rides and carnival.",
      image: "/tourism/download (1).jpg",
      lat: 23.0010,
      lon: 72.5847,
      address: "Maninagar, Ahmedabad, Gujarat",
      category: "Leisure",
    },
    {
      id: 7,
      name: "Lothal",
      description: "Ancient Indus Valley Civilization port town with earliest dockyards.",
      image: "/tourism/lothal-1.jpg",
      lat: 22.5369,
      lon: 72.3835,
      address: "Lothal, Gujarat",
      category: "Historic",
    },
    {
      id: 8,
      name: "Saputara Hill Station",
      description: "Gujarat’s only hill station offering boating, trekking, gardens, cable car.",
      image: "/tourism/download (2).jpg",
      lat: 20.9600,
      lon: 73.7440,
      address: "Dang district, Gujarat",
      category: "Hill Station",
    },
    {
      id: 9,
      name: "Talaja Caves",
      description: "Ancient rock-cut Buddhist and Jain caves dating from circa 2nd century BCE/CE.",
      image: "/tourism/download (3).jpg",
      lat: 21.6800,
      lon: 71.6450,
      address: "Talaja, Bhavnagar district, Gujarat",
      category: "Heritage",
    },
  ];

  return NextResponse.json(data);
}
